name: argeym
description: AR Shooter Game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  socket_io_client: ^2.0.3+1
  camera: ^0.10.5+9
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  sensors_plus: ^4.0.2
  flutter_compass: ^0.8.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
